package main

import (
	"fmt"
	"os"
	"strconv"
	"time"
)

func main() {
	// Get arguments
	args := os.Args
	if len(args) == 1 {
		fmt.Println("root directory is missing")
		os.Exit(2)
	} else if len(args) == 2 {
		fmt.Println("author name is missing")
		os.Exit(2)
	}
	dir := args[1]
	author := args[2]

	// Year for license
	year := time.Now().Year()

	// MIT license
	var license = `MIT License

Copyright (c) ` + strconv.Itoa(year) + " " + author + `

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`

	// Create license file
	licenseFile, err := os.Create(dir + "/LICENSE")
	if err != nil {
		panic(err)
	}
	defer licenseFile.Close()

	// Write MIT license to license file
	_, err = licenseFile.Write([]byte(license))
	if err != nil {
		panic(err)
	}

	fmt.Println("LICENSE file saved successfully")

	// Create readme file
	readmeFile, err := os.Create(dir + "/README.md")
	if err != nil {
		panic(err)
	}
	defer readmeFile.Close()

	// Get directory tree for provided path
	err = getDirectoryTree(dir, "|- ")
	if err != nil {
		fmt.Println("Error creating directory tree:", err)
	}

	filesContents := getFilesContents()

	// Get readme generated by Gemini
	readme := newGetResponse(directoryTree, filesContents)

	// Write Gemini generated readme into readme file
	_, err = readmeFile.Write([]byte(readme))
	if err != nil {
		panic(err)
	}

	fmt.Println("README.md file saved successfully")
	os.Exit(0)
}
