package main

import (
	"fmt"
	"log"
	"os"

	"github.com/raziel-aleman/go-readme/internal/utils"
)

func main() {
	// Get arguments
	args := os.Args
	if len(args) == 1 {
		fmt.Println("root directory is missing")
		os.Exit(2)
	} else if len(args) == 2 {
		fmt.Println("author name is missing")
		os.Exit(2)
	}
	dir := args[1]
	author := args[2]

	// Create license file
	licenseFile, err := os.Create(dir + "/LICENSE")
	if err != nil {
		log.Fatalf("error creating LICENSE file: %v", err)
	}
	defer licenseFile.Close()

	// Write MIT license to license file
	_, err = licenseFile.Write([]byte(utils.GenerateLicense(author)))
	if err != nil {
		log.Fatalf("error writing to LICENSE file: %v", err)
	}

	fmt.Println("LICENSE file saved successfully")

	// Create readme file
	readmeFile, err := os.Create(dir + "/README.md")
	if err != nil {
		log.Fatalf("error creating README file: %v", err)
	}
	defer readmeFile.Close()

	// Get directory tree for provided path
	err = utils.GetDirectoryTree(dir, "|- ")
	if err != nil {
		log.Fatalf("Error creating directory tree: %v", err)
	}

	filesContents := utils.GetFilesContents()

	// Get readme generated by Gemini
	readme := utils.GenerateReadme(utils.DirectoryTree, filesContents)

	// Write Gemini generated readme into readme file
	_, err = readmeFile.Write([]byte(readme))
	if err != nil {
		log.Fatalf("error writing to README file: %v", err)
	}

	fmt.Println("README.md file saved successfully")
	os.Exit(0)
}
